import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  ordering: [
    {
      "slug": "quickstart"
    },
    {
      "slug": "installation"
    },
    {
      "slug": "features",
      "children": [
        {
          "slug": "session-management"
        }
      ]
    },
    {
      "slug": "configuration",
      "children": [
        {
          "slug": "database"
        },
        {
          "slug": "deployment"
        },
        {
          "slug": "environment"
        }
      ]
    },
    {
      "slug": "guides",
      "children": [
        {
          "slug": "cli-usage"
        }
      ]
    },
    {
      "slug": "api",
      "children": [
        {
          "slug": "cli",
          "children": [
            {
              "slug": "start"
            }
          ]
        },
        {
          "slug": "config",
          "children": [
            {
              "slug": "access-config"
            },
            {
              "slug": "events-config"
            },
            {
              "slug": "metadata-config"
            }
          ]
        }
      ]
    }
  ],
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
